version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter analyze
      # - run: flutter test # Disabled for the moment due to known issues with internationalized apps.
      - run: flutter -v build apk 